### ISSUE TITLE
스펙에 관한 질문

### ISSUE THREAD

**Issue by tirr-c** [kmc7468/Aheuiplusplus#1]
스펙에 몇 가지 질문이 있습니다.

* 예외 처리 문서를 보면, 코드에서 사용자가 `\f`, `\n`, `\r`, `\t`, `\b`를 입력한 것을 받아올 수 없는 것으로 보입니다(문자 입력도, 문자열 입력도 이 다섯 문자를 받아들이지 않음). 이 다섯 문자를 읽어들일 수 없도록 설계된 건가요?
* `아니희` 이 코드는 종료되는 것이 맞나요? 스펙에 따르면 `니` 명령을 실행하기 위한 피연산자가 부족하기 때문에 `ㅣ`에 따라 진행 방향을 뒤집는 대신 이전에 정상적으로 실행된 명령인 `아`의 진행 방향을 따라야 합니다.
* 정수 타입이 1의 보수 표현을 따르는데, 그러면 0의 표현 방법이 두 가지가 됩니다(`0x00000000`, `0xffffffff`). 이것을 의도한 것이 맞나요?
* 소수 타입은 IEEE 754를 따르나요?

**Comment by kmc7468** [comment]
안녕하세요, static입니다.
- 문자에서 공백 문자를 받아들일 수 없다는 부분은 제가 실수로 수정을 하지 않은 것입니다. [명령 ㅂ](https://github.com/kmc7468/Aheuiplusplus/wiki/%EB%AA%85%EB%A0%B9-%E3%85%82) 문서를 보시면 공백 문자도 받아들일 수 있다고 명시가 되어 있는데, 이 부분이 올바른 동작입니다. 이 부분은 수정하겠습니다. 문자열 같은 경우에는 그렇게 설계한 것이 맞습니다. 차기 표준에서 함수가 추가되면 공백 문자도 포함하여 읽는 함수를 추가할 계획이 있습니다(C++의 `std::getline` 함수에 해당합니다.).
- 결과만 말씀드리자면 종료됩니다. 그러나 아희 호환 모드가 켜져있냐 꺼져있냐에 따라 내부 처리 과정이 달라집니다.
    - 먼저 아희 호환 모드가 꺼져 있는 경우입니다. 이 경우에는 말씀하신대로 동작합니다.
    - 두번째로는 아희 호환 모드가 켜져 있는 경우입니다. 우선 중성에 근거하여 진행 방향을 뒤집습니다(즉, `ㅓ`와 같은 효과를 냅니다.). 그러나 명령이 무시되었으므로 방향이 뒤집어져 `ㅏ`와 같은 효과를 내게 됩니다. 그리하여 `니` 다음에 `희`가 실행되게 되어 종료됩니다.
- 최소 표현 범위이지 반드시 해당 표현 범위만 지원할 수 있어야 한다는 의미는 아닙니다.
- IEEE754에서 정의하는 64비트 배정도 부동소수점의 표현 범위를 모두 표현할 수 있다면 다른 부동소수점 표준 또는 고정소수점 방식을 사용하여도 무방합니다.

추가 질문이 있으시면 이 이슈에 계속 남겨주시고, 질문이 없으시다면 이슈를 닫아주시면 될 것 같습니다. 감사합니다.

**Comment by tirr-c** [comment]
감사합니다. 나중에 구현체 작성할 때 막히면 다시 질문하겠습니다.
